services:
  server:
    build: ./server
    container_name: casino-server
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3779:3779"
    env_file:
      - ./server/.env
    volumes:
      - ./server/users.db:/app/users.db
      - ./server/support.db:/app/support.db
      - ./server/backups:/app/backups

  client:
    build: ./client
    container_name: casino-client
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "80:80"
    depends_on:
      - server
